### ISSUE TITLE
Strange issue with network connect

### ISSUE THREAD

**Issue by shoxxdj** [mafintosh/docker-remote-api#7]
Hello, 

I'm trying to connect to a network using .post('/networks...') 
Before I've created a network and create/started a container. 
I have both ID on network and container varialbe

`    docky.post('/networks/'+network+'/connect',{json:{'Container':container}},function(err,toto){
`

I allways get: 
`SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
`

Just cant understand why ..
Can you help ? :) 
Thx!

**Comment by styfle** [comment]
Which version are you using?

Is this a new problem that you started having with [v5.0.0](https://github.com/mafintosh/docker-remote-api/releases/tag/v5.0.0) or did you have the problem before?

**Comment by shoxxdj** [comment]
Sorry, I should have write it :)
It occurs on 4.4.X (can not remember the X) and 5.0

**Comment by styfle** [comment]
Thanks 👍 

I just checked [the documentation](https://docs.docker.com/engine/api/v1.24/#connect-a-container-to-a-network) and it looks like `Container` is supposed to be lowercase `container`.

See the "JSON parameters" section.

It looks like the response returns an uppercase `Container` so it's a bit confusing.

Does changing you code fix the problem?

```
docky.post('/networks/'+network+'/connect',{json:{'container':container}},function(err,toto)
```

**Comment by shoxxdj** [comment]
Hmm nop, still have the same issue. 
Code : 
```
function connectToNetwork(container,network){
  return new Promise(function(fulfill,reject){
    docky.post('/networks/'+network+'/connect',{json:{'container':container}},function(err,toto){
      if(!err){
        fulfill();
      }
      else{
        reject();
      }
    });
  });
}
```
And error : 
```SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at [...]/server/node_modules/docker-remote-api/index.js:26:18
    at ConcatStream.<anonymous> ([...]/server/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:185:15)
    at finishMaybe ([...]/server/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:475:14)
    at endWritable ([...]/server/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:485:3)
    at ConcatStream.Writable.end ([...]/server/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:455:41)
    at IncomingMessage.onend (_stream_readable.js:602:10)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

**Comment by styfle** [comment]
Are you sure the network exists?
Try using the Network ID instead of the name.

**Comment by shoxxdj** [comment]
yep 100% sure, I've tested with the name, the ID I allways got the same response.. 
maybe I'll try without the library
